### ISSUE TITLE
Scrolling tabs quickly using swipe gestures will lead to a crash.

### ISSUE THREAD

**Issue by lfarah** [lucoceano/Pager#6]
This issue is also present on the [Objective-C's version of Pager](http://github.com/lucoceano/CKViewPager/issues/4)

made by @ycastonguay-cbc

**Comment by lfarah** [comment]
The library ICViewPager also had this problem and [they managed to fix](https://github.com/iltercengiz/ICViewPager/issues/67)

**Comment by lfarah** [comment]
@ycastonguay-cbc It's fixed now!

**Comment by marciogranzotto** [comment]
I'm still experiencing this issue at `1.0.10`. The app stops at line 466 of `PagerController.swift`. Here's the log:

```
*** Terminating app due to uncaught exception 'UIViewControllerHierarchyInconsistency', reason: 'A view can only be associated with at most one view controller at a time! View <UITableView: 0x15e1ea800; frame = (0 0; 375 510); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x15ea58a30>; layer = <CALayer: 0x15ea02bd0>; contentOffset: {0, 0}; contentSize: {375, 36102.5}> is associated with <UIViewController: 0x15e9c4770>. Clear this association before associating this view with <UIViewController: 0x15ea8fc50>.'
```

**Comment by marciogranzotto** [comment]
@lfarah should I open a new issue?

**Comment by lfarah** [comment]
@marciogranzotto yeah, please open an new issue
